name: "🕹️ Issue Triage Labels"

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "needs-triage" if issue already has an assignee
        if: ${{ github.event.issue.assignee != null }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: needs-triage

      - name: Add "needs-triage" if issue has no assignee
        if: ${{ github.event.issue.assignee == null }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-triage
